# Autogenerated (Do not edit)

require "formula"
require_relative "lib/private_strategy"

class Pryrite < Formula
  desc "pryrite is a markdown executor program"
  homepage "https://github.com/1xyz/pryrite"
  url "https://github.com/1xyz/pryrite/releases/download/0.10.19/pryrite-darwin-amd64-0.10.19.zip"
  sha256 "f0ab1d1db568069b7283e3c4f19acfb642920a3e8e40ffbd864cdd60011bcd2c"
  head "https://github.com/1xyz/homebrew-pryrite.git"
  # depends_on "coreutils"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"pryrite"
  end

  def caveats
    <<~EOS
      pryrite is a markdown executor program.

      * Once installed, you can run the following command to help get started

        $ pryrite --help

    EOS
  end

  # Homebrew requires tests.
  test do
    assert_match "0.10.19", shell_output("#{bin}/pryrite --version", 2)
  end
end