# Autogenerated (Do not edit)

require "formula"
require_relative "lib/private_strategy"

class Pryrite < Formula
  desc "pryrite is a markdown executor program"
  homepage "https://github.com/1xyz/pryrite"
  url "https://github.com/1xyz/pryrite/releases/download/0.10.18/pryrite-darwin-amd64-0.10.18.zip"
  sha256 "eb49fb5a5b6be72785ebed6227868c03d33764ecfae698b87619b916bb288867"
  head "https://github.com/1xyz/homebrew-pryrite.git"
  # depends_on "coreutils"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"pryrite"
  end

  def caveats
    <<~EOS
      pryrite is a markdown executor program.

      * Once installed, you can run the following command to help get started

        $ pryrite --help

    EOS
  end

  # Homebrew requires tests.
  test do
    assert_match "0.10.18", shell_output("#{bin}/pryrite --version", 2)
  end
end