# Autogenerated (Do not edit)

require "formula"
require_relative "lib/private_strategy"

class Pryrite < Formula
  desc "pryrite is a markdown executor program"
  homepage "https://github.com/1xyz/pryrite"
  url "https://github.com/1xyz/pryrite/releases/download/0.10.20/pryrite-darwin-amd64-0.10.20.zip"
  sha256 "492846d5cc616056d62939ae4dcb4491bbe6a9dd4357ce03d1715515a06e30f7"
  head "https://github.com/1xyz/homebrew-pryrite.git"
  # depends_on "coreutils"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"pryrite"
  end

  def caveats
    <<~EOS
      pryrite is a markdown executor program.

      * Once installed, you can run the following command to help get started

        $ pryrite --help

    EOS
  end

  # Homebrew requires tests.
  test do
    assert_match "0.10.20", shell_output("#{bin}/pryrite --version", 2)
  end
end